version: '3'

networks:
  fourtwoone:

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx_421
    ports: 
      - "8888:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    networks: 
      - fourtwoone

  php:
    image: php:7.3-fpm-alpine
    container_name: php_421
    volumes:
      - ./src:/var/www/html:delegated
    expose:
      - "9000"
    networks:
      - fourtwoone
      
